# Generated by Django 3.1.2 on 2020-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201119_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
