# Generated by Django 3.1.2 on 2020-11-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_myorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrders',
        ),
    ]
