# Generated by Django 3.1.2 on 2020-11-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.CharField(default='', max_length=2550),
        ),
    ]
