# Generated by Django 3.1.2 on 2020-11-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201128_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description1',
            field=models.CharField(blank=True, default='', max_length=2550, null=True),
        ),
    ]
