# Generated by Django 3.1.2 on 2020-11-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201128_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
