# Generated by Django 3.1.2 on 2020-12-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201128_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='customer',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
