# Generated by Django 3.1.2 on 2020-12-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_myorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='No customer', max_length=200),
        ),
    ]
