# Generated by Django 3.1.2 on 2020-12-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.order')),
            ],
            bases=('store.order',),
        ),
    ]
