# Generated by Django 3.1.2 on 2020-12-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
