# Generated by Django 3.1.2 on 2020-12-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
