# Generated by Django 3.1.2 on 2020-12-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='user_name',
        ),
    ]
