# Generated by Django 3.1.2 on 2020-12-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20201215_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
