# Generated by Django 3.1.2 on 2020-12-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_Qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
