# Generated by Django 3.1.2 on 2020-12-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20201215_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='product_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_Qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
    ]
