# Generated by Django 3.1.2 on 2020-12-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20201215_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
