# Generated by Django 3.1.2 on 2020-12-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20201215_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='order_id',
        ),
    ]
