# Generated by Django 3.1.2 on 2020-12-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20201216_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
