# Generated by Django 3.1.2 on 2020-12-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
