# Generated by Django 3.1.2 on 2020-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_customer_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
