# Generated by Django 3.1.2 on 2020-12-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20201219_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='order_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
