# Generated by Django 3.1.2 on 2020-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_myorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='shipping_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
