# Generated by Django 3.1.2 on 2020-12-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_myorder_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='customer_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
