# Generated by Django 3.1.2 on 2020-12-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_myorder_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.CharField(default='blank', max_length=200),
        ),
    ]
